version: '3.8'
services:
  app:
    build: .
    container_name: cmg-app
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION}"
        awslogs-group: "${AWSLOGS_GROUP}"
        awslogs-stream: "${AWSLOGS_STREAM}"
