[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
exclude = ["venv"]
extend-ignore = "E203,E711"
per-file-ignores = ["__init__.py:F401"]

[tool.mypy]
exclude = "(venv|migrations)/"
plugins = ["pydantic.mypy"]
strict_optional = true
check_untyped_defs = true
warn_redundant_casts = true
disable_error_code = ["str-format", "import-untyped", "assignment"]
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_incomplete_stub = true
ignore_missing_imports = true
no_implicit_optional = true
warn_no_return = false
