"""init

Revision ID: 0000
Revises: 
Create Date: 2024-10-29 18:40:54.188708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('companies',
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('sic', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statements',
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('filing_date', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.ForeignKeyConstraint(['tag'], ['categories.tag'], ),
    sa.PrimaryKeyConstraint('accession_number', 'period', 'filing_date', 'report_date', 'cik', 'tag')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('Free', 'Basic', 'Premium', name='subscriptiontype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CANCELED', 'FULFILLED', 'EXPIRED', name='fulfillmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('financial_statements')
    op.drop_table('users')
    op.drop_table('companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
