"""add new columns for companies

Revision ID: 0004
Revises: 0003
Create Date: 2024-11-19 16:32:40.135946

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("sector", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("industry", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("country", sa.String(), nullable=True))
    op.execute(
        """
        ALTER TABLE financial_statements
        ALTER COLUMN value TYPE MONEY
        USING value::numeric::money;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_statements",
        "value",
        existing_type=postgresql.MONEY(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("companies", "country")
    op.drop_column("companies", "industry")
    op.drop_column("companies", "sector")
    # ### end Alembic commands ###
