"""add_fmp_table

Revision ID: 0005
Revises: 0004
Create Date: 2025-01-10 14:59:02.753509

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fmp_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("value_definition", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "type", sa.Enum("api_tag", "custom_formula", "exact_value", name="fmpcategorydefinitiontype"), nullable=True
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.CheckConstraint("priority >= 1"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label", "value_definition", name="uq_label_value_definition"),
    )
    op.create_index(op.f("ix_fmp_categories_id"), "fmp_categories", ["id"], unique=False)
    op.create_table(
        "fmp_statements",
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("filing_date", sa.String(), nullable=False),
        sa.Column("report_date", sa.String(), nullable=False),
        sa.Column("value", postgresql.MONEY(), nullable=True),
        sa.Column("cik", sa.String(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["fmp_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cik"],
            ["companies.cik"],
        ),
        sa.PrimaryKeyConstraint("period", "filing_date", "report_date", "cik", "category_id"),
    )
    op.alter_column("categories", "value_definition", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "value_definition", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("fmp_statements")
    op.drop_index(op.f("ix_fmp_categories_id"), table_name="fmp_categories")
    op.drop_table("fmp_categories")
    # ### end Alembic commands ###
