"""replace_money_column

Revision ID: 0006
Revises: 0005
Create Date: 2025-02-24 17:13:20.157965

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_statements",
        "value",
        existing_type=postgresql.MONEY(),
        type_=sa.Numeric(precision=38, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "fmp_statements",
        "value",
        existing_type=postgresql.MONEY(),
        type_=sa.Numeric(precision=38, scale=4),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fmp_statements",
        "value",
        existing_type=sa.Numeric(precision=16, scale=4),
        type_=postgresql.MONEY(),
        existing_nullable=True,
    )
    op.alter_column(
        "financial_statements",
        "value",
        existing_type=sa.Numeric(precision=16, scale=4),
        type_=postgresql.MONEY(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
