"""add_company_columns

Revision ID: 299094c68ad1
Revises: 0007
Create Date: 2025-03-12 13:24:40.828274

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("market_cap", sa.Numeric(precision=38, scale=2), nullable=True))
    op.add_column("companies", sa.Column("P/E", sa.Numeric(precision=38, scale=2), nullable=True))
    op.add_column("companies", sa.Column("price", sa.Numeric(precision=38, scale=2), nullable=True))
    op.add_column("companies", sa.Column("change", sa.Numeric(precision=38, scale=2), nullable=True))
    op.add_column("companies", sa.Column("volume", sa.Integer(), nullable=True))
    op.alter_column("companies", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("companies", "ticker", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "ticker", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("companies", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("companies", "volume")
    op.drop_column("companies", "change")
    op.drop_column("companies", "price")
    op.drop_column("companies", "P/E")
    op.drop_column("companies", "market_cap")
    # ### end Alembic commands ###
